name: settings
description: Global settings for Alter Bahnhof Web Server
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  google_fonts:

dev_dependencies:
  lints:

flutter:
  uses-material-design: true
