name: server
description: The application server for Alter Bahnhof
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  model:
    path: '../model'
  http:
  intl:
  mongo_dart:
  settings:
    path: '../settings'
  shelf:
  shelf_router:
  utils:
    path: '../utils'

dev_dependencies:
  lints:
