name: alter_bahnhof_widgets
description: "Widgets for Alter Bahnhof Web site"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  http:
  intl:
  model:
    path: '../model'
  settings:
    path: '../settings'
  utils:
    path: '../utils'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
