name: csv2mongo
description: A CLI to process exported data from CalendarApp
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.5

dependencies:
  csv:
  initialize_db:
    path: '../initialize_db'
  intl:
  mongo_dart:
  settings:
    path: '../settings'
dev_dependencies:
  lints:
  test:
