name: csv2mongo
description: A CLI to process exported data from CalendarApp
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  csv:
  intl:
  mongo_dart:
  settings:
    path: '../settings'
dev_dependencies:
  lints:
  test:
